name: Docker Containers

on:
  pull_request:
    branches: [ 'main', 'develop' ]

env:
  REGISTRY: ghcr.io
  DEV_TAG: latest
  RELEASE_TAG: v0.1.0

jobs:
  docker-compose:
    timeout-minutes: 5
    runs-on:
      ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build Containers
      run: docker-compose -f docker-compose.yml --build
