name: Build Angular Client

on:
  push:
    branches: [ "develop", "feature/*" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: concurrence-client
  TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
        tags: |
          # set latest tag for master branch
          type=raw,value={{tag}},enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'develop') }}
          
    - name: Build and push Angular Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./ConcurrenceClient
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
