name: Build Angular Client

on:
  pull_request:
    branches: [ "main", "develop" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: concurrence-client
  TAG: latest
  NODE_VERSION: 12.11.1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: Install Dependencies
        working-directory: ./ConcurrenceClient
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm ci
          
      - name: Build
        working-directory: ./ConcurrenceClient
        run: |
          npm run build -- --prod
          
      - name: Lint
        working-directory: ./ConcurrenceClient
        run: |
          npm run lint
          
      - name: Test
        working-directory: ./ConcurrenceClient
        run: |
          npm run test -- --prod
